// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS_B2hHjc_f8fTy4GwnrO2wDkIQeFkfQU',
    appId: '1:255838222961:web:ce7499b2baf83ff312f9d0',
    messagingSenderId: '255838222961',
    projectId: 'sayac-app-fatura',
    authDomain: 'sayac-app-fatura.firebaseapp.com',
    storageBucket: 'sayac-app-fatura.firebasestorage.app',
    measurementId: 'G-668TYG185K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9wpHZFlaUCqAYzHAzsqLs9MnNMn8CklI',
    appId: '1:255838222961:android:525c5520e7fae72112f9d0',
    messagingSenderId: '255838222961',
    projectId: 'sayac-app-fatura',
    storageBucket: 'sayac-app-fatura.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmO9qtySuS0mJ83mAstqlbdPBIHDrI4lw',
    appId: '1:255838222961:ios:45fe6deef3224fbf12f9d0',
    messagingSenderId: '255838222961',
    projectId: 'sayac-app-fatura',
    storageBucket: 'sayac-app-fatura.firebasestorage.app',
    iosBundleId: 'com.example.sayacfaturapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmO9qtySuS0mJ83mAstqlbdPBIHDrI4lw',
    appId: '1:255838222961:ios:45fe6deef3224fbf12f9d0',
    messagingSenderId: '255838222961',
    projectId: 'sayac-app-fatura',
    storageBucket: 'sayac-app-fatura.firebasestorage.app',
    iosBundleId: 'com.example.sayacfaturapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS_B2hHjc_f8fTy4GwnrO2wDkIQeFkfQU',
    appId: '1:255838222961:web:3c112e32178e418b12f9d0',
    messagingSenderId: '255838222961',
    projectId: 'sayac-app-fatura',
    authDomain: 'sayac-app-fatura.firebaseapp.com',
    storageBucket: 'sayac-app-fatura.firebasestorage.app',
    measurementId: 'G-9M4CQ0NVLY',
  );
}
